### ISSUE TITLE
[Feature] Add an option/key to choose video quality to download

### ISSUE THREAD

**Issue by shad0wrunner** [madiele/vod2pod-rss#200]
As we don't need to download the best quality - it would be great to have an option to select a video quality that would be downloaded in order to transcode it to audio. E.g. 144, 240, 360.

This would greatly increase speed of download and allow for smoother transcoding. especially in situations where there is any kind of download limit on owned servers' side (or restrictions on YouTube download speed)

**Comment by madiele** [comment]
Hi, vod2pod is already setup so it will only fetch the audio track and transcode that to mp3, so it's already optimized, no need for a setting to choose video quality, since there is no video to be trancoded...

you can test this by installing yt-dlp on you linux machine and running

`yt-dlp.exe -f bestaudio --get-url "https://www.youtube.com/watch?v=EGWRhyoUF3Y"`

which is the command vod2pod runs to fetch the stream URI, give the output to vlc and you will see that it's just plain audio with no video

Unfortunately there is nothing to be done to improve the download speed on vod2pod side, the only thing you can try is to move to the beta image as it always has the most recent version of yt-dlp and se if stuff improves

**Comment by shad0wrunner** [comment]
Thanks for the clarification and sorry I was mistaken about how vdo2pod works.

**Comment by madiele** [comment]
no problem, I could improve the documentation to dispel any doubts like this
