### ISSUE TITLE
Separete IU Web port and XML port

### ISSUE THREAD

**Issue by cansi22** [madiele/vod2pod-rss#219]
If you want to use it with an application that uses an external URL (PocketCast), you need to publish this service on the web and anyone will be able to access the website and my service.

In case the website server and the XML server are on separate ports, only the latter can be made public with the reverse proxy, which makes it more secure.

**Comment by madiele** [comment]
I kinda follow what are you saying, but the website is just a webpage that generates the correct url for the service, you can fully use the service without so you'll just hide the easy way to use vod2pod, if you want to hide the frontend I suggest you to just use a really ugly subfolder to host it, https will hide the url for any eventual man in the middle, I know it's not much but it's something. 

Also some reverse proxy like nginx do allow you to have special rules based on a path, I know because that's how I use mine behind authentik

In the future I would like to add some basic auth feature to vod2pod to make sure only the owner has access to the feeds, but I have very little time for side projects lately...
