### ISSUE TITLE
Setting to increase feed length?

### ISSUE THREAD

**Issue by blairun** [madiele/vod2pod-rss#90]
app version: 1.0.2

- [ ] twitch api key set
- [x] youtube api key set

______
issue description:
RSS feeds seem limited to about 50 items, which excludes old videos.  Could a setting be added to increase the feed length?

E.g. a feed for https://www.youtube.com/@LastWeekTonight only goes back Oct 2021, rather than including the full list of videos that go back several more years.

<your issue here be sure to include logs if you can>

**Comment by madiele** [comment]
50 items is just the limit of elements you can fetch in a single call with the youtube API, currently the actual feed generation is made by [amckee/PodTube](https://github.com/amckee/PodTube) which is not my project, looking at the source code it seems that there is already a page logic but it seems it was manually disabled 2 years ago, I'll open an issue there and we'll see

**Comment by amckee** [comment]
After testing, this does appear to end up being an issue with the Youtube API limitations, though I am hoping to find a workaround:

```
2023-08-11 18:29:52,354 [INFO] 302 GET /youtube/user/@LastWeekTonight (::1) 313.12ms
2023-08-11 18:29:52,600 [INFO] Channel: UC3XTzVzaHQEd30rQbuvCtTQ (LastWeekTonight)
2023-08-11 18:29:53,397 [INFO] Got 56 videos from 3 pages
```

**Comment by madiele** [comment]
Thanks a lot, if I can help in anyway just let me know ✌️

**Comment by madiele** [comment]
@blairun the next release will fix this issue, I've completely rewritten the way i fetch the feed, from the next release the feed is generated all inside vod2pod with no need for podtube anymore (in fact you will be able to remove the section from the docker-compose, more info on the release notes when I've tested it for some week on the beta image).

I've made it so that the feed will fetch up to 300 videos!

in the next few days i will publish a beta image with the update, once is ready if you want a preview use `:beta` instead of `:latest` in your docker compose

**Comment by madiele** [comment]
closing with release v1.1.0 #130

**Comment by blairun** [comment]
Just updated and everything's working well. Thanks!
